# ansible version: 1.8
- hosts: web
  tasks:
    - sysctl: name={{item.name}} value={{item.value}} state=present sysctl_set=yes
      with_items:
          - { name: 'net.ipv4.ip_local_port_range', value: "'1024 65500'" }
          - { name: 'net.core.rmem_max', value: '16777216' }
          - { name: 'net.core.wmem_max', value: '16777216' }
          - { name: 'net.ipv4.tcp_rmem', value: "'4096 87380 16777216'" }
          - { name: 'net.ipv4.tcp_wmem', value: "'4096 65536 16777216'" }
          - { name: 'net.ipv4.tcp_mem', value: "'786432 2097152 3145728'" }
          - { name: 'net.ipv4.tcp_fin_timeout', value: 10 }
          - { name: 'net.ipv4.tcp_tw_reuse', value: 1 }
          - { name: 'net.ipv4.tcp_tw_recycle', value: 1 }
          - { name: 'net.ipv4.tcp_timestamps', value: 0 }
          - { name: 'net.ipv4.tcp_window_scaling', value: 0 }
          - { name: 'net.ipv4.tcp_sack', value: 0 }
          - { name: 'net.core.netdev_max_backlog', value: 262144 }
          - { name: 'net.ipv4.tcp_max_syn_backlog', value: 262144 }
          - { name: 'net.ipv4.tcp_no_metrics_save', value: 1 }
          - { name: 'net.core.somaxconn', value: 262144 }
          - { name: 'net.ipv4.tcp_max_orphans', value: 262144 }
          - { name: 'net.ipv4.tcp_synack_retries', value: 2 }
          - { name: 'net.ipv4.tcp_syn_retries', value: 2 }
          - { name: 'net.ipv4.tcp_keepalive_time', value: 30 }
          - { name: 'net.ipv4.tcp_keepalive_probes', value: 3 }
          - { name: 'net.ipv4.tcp_keepalive_intvl', value: 30 }
          - { name: 'net.ipv4.tcp_max_tw_buckets', value: 8000 }
